### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

### ISSUE THREAD

**Issue by zoe-mcelderry** [diegoddox/react-redux-toastr#220] opened 2019-01-02 14:51 UTC
I'm getting a warning in my console output since upgrading my application to react v16 and react-redux-toastr to v7.4.5.

This occurs when I use toastr.confirm -- it looks like it is the toastr confirmation buttons that are causing the issue.

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `ToastrConfirm`.
    in ReduxConfirmButton (created by ToastrConfirm)
    in div (created by ToastrConfirm)
    in div (created by ToastrConfirm)
    in div (created by ToastrConfirm)
    in ToastrConfirm (created by ReduxToastr)
    in span (created by ReduxToastr)
    in ReduxToastr (created by Connect(ReduxToastr))
    in Connect(ReduxToastr) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in AppContainer
```

**Comment by diegoddox** [comment] 2019-01-03 05:45
Thanks @zoe-mcelderry, not sure when I will be able to look at it.

**Comment by zoe-mcelderry** [comment] 2019-01-03 11:09
@diegoddox  No problem.  It doesn't appear to be causing us any major issues in terms of functionality, it's just disconcerting to get the warning in the console.

**Comment by henriqueweiand** [comment] 2019-01-17 16:20
i have too this problem

![captura de tela 2019-01-17 as 14 17 38](https://user-images.githubusercontent.com/6539492/51332555-1b15aa80-1a63-11e9-8f1e-7f14bcd545dd.png)

**Comment by irvelervel** [comment] 2019-01-19 15:06
Confirmed here as well.

**Comment by rahadkc** [comment] 2019-01-27 09:57
I am having same problem and my page is broken. Need a solution. Thanks for your great plugin.

**Comment by KozhevnikovDmitry** [comment] 2019-02-13 06:49
+1

**Comment by ben-bcn** [comment] 2019-02-14 04:12
Same problem here

**Comment by kimmy** [comment] 2019-03-11 02:46
+1

**Comment by zachweinberg** [comment] 2019-03-23 16:39
Same problem

**Comment by learningassistant** [comment] 2019-03-28 11:41
+1

**Comment by ghost** [comment] 2019-03-28 13:04
+1, @diegoddox any updates?

**Comment by YuriScarbaci** [comment] 2019-04-16 16:50
+1 same problem 
![Confirm toastr](https://user-images.githubusercontent.com/10579158/56228427-1bc8d780-6078-11e9-90b6-ea06876e2860.png)

npm packages versions (only issue relatives ones):
```
{
  "dependencies": {
      "react": "^16.8.1",
      "react-redux": "^6.0.0",
      "redux": "^4.0.1",
      "redux-thunk": "^2.3.0"
      "react-redux-toastr": "^7.4.8",
   }
}
```

**Comment by gaupoit** [comment] 2019-04-18 07:48
+1

**Comment by diegoddox** [comment] 2019-04-24 17:00
Thanks everyone, this should be fixed on the latest.
Can someone confirm for me?

**Comment by diegoddox** [comment] 2019-04-24 17:25
I will close but in case it doesn't working feel free to reopen.

**Comment by skychavda** [comment] 2019-07-03 11:59
Here is a solution to this problem
[Solution to function component issue](https://github.com/reactjs/reactjs.org/issues/2120)

**Comment by diegoddox** [comment] 2019-07-04 12:44
@skychavda are you facing this issue if so could you please provide the `-v` that you're using?

**Comment by skychavda** [comment] 2019-07-11 14:47
@diegoddox Yes I have faced that issue but I've solved this issue and also gave the solution. Which is on the above comment. 
I am using React version - 16.6.0

**Comment by amzbiz** [comment] 2019-07-26 00:06
7.4.9 version works for me with React 16.8.3 @diegoddox

**Closed as completed** 2019-10-05 08:06 UTC
Labels: bug

**Comment by Muneem** [comment] 2020-07-12 10:14
@diegoddox still facing the same issue with React 16.13.1

**Comment by buildswitharpit** [comment] 2020-09-03 13:14
@diegoddox still facing the same issue with react 16.13.1
