### ISSUE TITLE
ToastrConfirm does not close if you show an error upon ok or cancel

### ISSUE THREAD

**Issue by RaitoBezarius** [diegoddox/react-redux-toastr#11] opened 2016-03-03 11:55 UTC
Hi!

It seems like that something is preventing the ToastrConfirm from closing when you dispatch a toastr in the ok or cancel handler.

It causes something like:

ok clicked → setTransition(false) (hiding = true) → add a new toastr → componentDidUpdate on ToastrConfirm (hiding = false) → once animation is complete, hiding is false so we don't remove the overlay.

At least, this is what I found by debugging.

**Comment by ashelkov** [comment] 2016-03-03 16:33
+1! have the same problem

**Comment by diegoddox** [comment] 2016-03-03 19:46
I was not able to reproduce.

1. can you please tell me if everything else works find?
2. This only happen when you fire a `toastr` in a `ToastrConfirm` callback?
3. what (browser and version) are you using?

**Comment by diegoddox** [comment] 2016-03-03 20:05
I have update the `demo` app to fire a `toastr` on a `ToastrConfirm` callback (ok/cancel).
can you please clone the repo and run the `demo` app and tell me what's happen?

`git clone https://github.com/diegoddox/react-redux-toastr.git`
`cd react-redux-toastr/demo`
`npm install`
`npm start`

**Comment by vladSumy** [comment] 2016-03-04 07:57
Problem-1
1. We call toastr.konfirm

## 2. In the event of approx (toaster.confirm) perform PROMIS. Depending on the result, we perform PROMIS (toastr.success) and if earlier PROMIS is executed, the screen is locked on Confirming

```
const toastrConfirmOptions = {
  onOk: () => {
    const { removeReport } = this.props
    removeReport({id: report.id})
      .then((response) => toastr.success('Report has been successfully deleted'))
      .catch((response) => response.error && toastr.error('Error', response.error))
  }
}
toastr.confirm(`Are you sure to delete a report ${report.email} ?`, toastrConfirmOptions)
```

---

Problem-2 
try to do manually dispatch events (actions.hideConfirm), but recalling the toastr.сonfirm lock screen disappears, but remains bunkeOutUp upon recall bounceInDown
const toastrConfirmOptions = {
      onOk: () => {
        const { removeReport,  hideConfirm} = this.props
        removeReport({id: report.id})
          .then((response) => {
                hideConfirm()
                toastr.success('Report has been successfully deleted'))
          }
          .catch((response) => response.error && toastr.error('Error', response.error))
      }
    }
    toastr.confirm(`Are you sure to delete a report ${report.email} ?`, toastrConfirmOptions)
P.S. 
I'd like to call when toastr.success... toastr.confirm correctly removed
Sorry for my English, and if you do not fully disclose the problem

**Comment by diegoddox** [comment] 2016-03-05 15:05
@vladSumy 
1. Sorry but I not really understand what you are trying to say.
2. why are you calling the `hideConfirm` on the `onOk` callback?

can you please provide some screenshots?

**Comment by diegoddox** [comment] 2016-03-05 15:05
@RaitoBezarius have you try the demo?

**Comment by diegoddox** [comment] 2016-03-05 16:24
After a while I was able to reproduce the issue and for some reason the new `toastr` animation was preventing the func `_removeConfirm` of running.

This is fixed (I HOPE :D) the ok and cancel callback will be fire when the `confirm` animation is done.

@RaitoBezarius, @ashelkov and @vladSumy can you please update and if you still get the same error please re-open this issue.

**Comment by RaitoBezarius** [comment] 2016-03-06 14:49
Awesome, thanks @diegoddox !

**Comment by diegoddox** [comment] 2016-03-06 14:53
@RaitoBezarius you welcome, please test and see if works

**Comment by ashelkov** [comment] 2016-03-07 08:58
Thank you! It's fixed now!

**Comment by diegoddox** [comment] 2016-03-07 10:51
@ashelkov you are welcome! thanks for your feedback!

**Closed as completed** 2016-03-10 11:01 UTC
