### ISSUE TITLE
Time-travel side-effects problem

### ISSUE THREAD

**Issue by Spiralis** [diegoddox/react-redux-toastr#43] opened 2016-08-10 15:46 UTC
Hi,

Thanks for a great project. I looked at this primarily due to being able to do time-travel on my apps, also for UI notifications. 

But, I think I have found a bug. I demoed my project today for a colleague and used time-travel to show off some parts of it. I then noticed that the toastr remove actions re-fired. Could it be that the remove-event is not controlled by a timer from within the original add-action? Or that the removal-timer is somehow dependent on the rendering of the page? 

If so, then I think time-travel is not going to work, because it will create new remove-actions also for old notifications that have already been both added and removed already. Without this the whole point of using the `react-redux-toastr` becomes moot. I think that the removal timer has to be set from the original show action, which makes sure that it is not re-fired just because a state is rendered.

Time-travelling should never fire new actions by itself. The user could do stuff during time-travel that will make the app mutate away from the original state, yes. And - if the app depends on polling or somehow updating it's state based on live data from external source then that will of course also lead to extra actions. If I am debugging my app (that has none of the above side-effects), using an exported state-list from e.g. a user, then I would not expect any actions to fire, unless I explicitly executes them myself. 

Please correct me if I am wrong in any of my assumptions here.

**Comment by diegoddox** [comment] 2016-08-12 06:33
Hi @Spiralis,
You're right, the remove action is fire from the `toastr` `component`, I will take a look in to it ASAP.

**Comment by diegoddox** [comment] 2016-08-19 20:03
Hi @Spiralis,

I was not able to reproduce this issue, only in the `demo app` with the `error` `toastr`.

But this is because the `toastr` has `props` `timeOut` and a custom `component`.
The `timeOut` is set to 0, this will prevent the `toastr` to auto `remove` and inside the custom `component` I'm dispatching a `remove` `action` 

ex:

```
const MyComp = props => {
  /*
   * Because we are dispatching a remove action from the
   * custom component the time-travel will have no effect on it, so no matter
   * whats happen this action will fire
   */ 
  setTimeout(() => props.remove(), 4000);
  return <h2>Hello {props.name}</h2>;
};

toastr.error('## Error', {
  timeOut: 0, // this will prevent the auto remove.
  component: (<MyComp name="Jesus" />)
});
```

Could you please provide me the version you are using and if you're doing something similar to the example above

**Comment by Spiralis** [comment] 2016-08-21 15:21
The current version of my project is in a state of rearranging stuff, so I can't provide an example directly unfortunately, I think. 

But, from what I can get from it, it looks like this:
- I have a ReduxToastr element in the layout element that looks like this:

```
    <ReduxToastr
        timeOut={5000}
        newestOnTop={true}
        position="top-right"/>     
```
- Then when I use any of the toastr action methods (`info`, `error`, etc) I never specify any explicit timeout (or component):

```
    toastr.info("Button clicked");
```

Not sure if that helps replicate the issue?

**Comment by diegoddox** [comment] 2016-08-22 17:40
@Spiralis can u please update ot lasted and tell me if you still can reproduce this issue.

**Comment by backnotprop** [comment] 2016-08-23 14:57
Seeing the same issues as @Spiralis. I use Redux-DevTools and the issue I am seeing  is that toastr history is being re-fired anytime a new reducer/container is rendered. Not explicitly time-traveling, but does result only when Redux-Devtools is keeping track of history. Disabling DevTools resolves the issue.

**Comment by diegoddox** [comment] 2016-08-23 18:54
@mdramos, @Spiralis  have/can u try with the lasted -v?

**Comment by diegoddox** [comment] 2016-08-25 19:58
@Spiralis @mdramos, any news on this issue!

**Comment by backnotprop** [comment] 2016-08-26 13:28
@diegoddox sorry for the late update! I've been on 3.6.2. Ill give the latest a shot sometime today

**Comment by diegoddox** [comment] 2016-08-29 16:51
@Spiralis @mdramos I will close the issue but feel free to re-open in case you still got the same issue.

**Closed as completed by diegoddox** 2016-08-29 16:51 UTC
Labels: bug, important

**Comment by Spiralis** [comment] 2016-09-08 19:07
@diegoddox Sorry, I have been caught up in other work. I will check tomorrow if time allows.

**Comment by diegoddox** [comment] 2016-09-08 19:11
@Spiralis np take your time.
