### ISSUE TITLE
Toastr timeout pauses after hover and toaster remains sticky

### ISSUE THREAD

**Issue by wasabitools** [diegoddox/react-redux-toastr#268] opened 2021-06-18 13:27 UTC
Toastr remains sticky after being hovered over. I added `removeOnHover: true` ,  `removeOnHoverTimeOut: 3000` without any success.

Any advice?

**Comment by diegoddox** [comment] 2021-06-24 09:50
Hi @natasafi,
Sorry for the late reply, are you still facing this issue?
no I cannot see what the issue could be.

**Comment by wasabitools** [comment] 2021-06-24 10:15
Hello @diegoddox ,

Thanks for the reply. Yes, the problem is that we have a Toastr that disappears normally _however_ if the user hovers over the toaster it becomes sticky and it doesn't fade. I tried to add the` removeOnHover: true `, `removeOnHoverTimeOut: 3000`  so even if it's hovered over it will still disappear but it didn't work. Is that a normal behaviour?

**Comment by diegoddox** [comment] 2021-06-24 10:18
No, it's not it should remove after, not sure when but will have a look.

**Comment by wasabitools** [comment] 2021-06-24 10:44
Thank you :)

**Comment by masiacra** [comment] 2021-11-11 11:12
Hello, I have the same issue. Is there any progress in solving the problem?

**Comment by diegoddox** [comment] 2021-11-20 18:22
@masiacra what version are u using?

**Comment by masiacra** [comment] 2021-11-22 06:57
@diegoddox, hello. "react-redux-toastr": "7.6.5"

**Comment by diegoddox** [comment] 2021-12-09 14:30
I'm not able to reproduce it, could any of you provide a reproducible link maybe on codesandbox.io ?

**Comment by masiacra** [comment] 2021-12-09 18:52
Sorry, diegoddox, but it seems like I did something wrong. Now it works fine

**Comment by diegoddox** [comment] 2021-12-10 09:49
I will close it, but incase anyone can provide a reproducible env feel free to re-open.

**Closed as completed by diegoddox** 2021-12-10 09:49 UTC
